FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./

RUN pip install -r requirements.txt 

COPY RealEstateModelTraining.py data/ ./model/

ENTRYPOINT ["python", "model/RealEstateModelTraining.py"]