FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./

RUN mkdir ./model

RUN pip install -r requirements.txt

COPY __init__.py features.py main.py db.py auth.py public.py prediction.py secure.py ./api/

EXPOSE 8000

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]